-- MySQL Script generated by MySQL Workbench
-- Fri Oct 22 12:45:53 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema learndb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema learndb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `learndb` DEFAULT CHARACTER SET utf8 ;
USE `learndb` ;

-- -----------------------------------------------------
-- Table `learndb`.`department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `learndb`.`department` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `learndb`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `learndb`.`employee` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `salary` INT NULL,
  `gender` VARCHAR(1) NULL,
  `department_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_dept_idx` (`department_id` ASC) VISIBLE,
  CONSTRAINT `fk_dept`
    FOREIGN KEY (`department_id`)
    REFERENCES `learndb`.`department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
